import React, {Component} from "react";
// Typo generated by Amplify CLI
// Not sure how to correct this while maintaining infrastructure as code
import {listMatchs, listTeams} from "../graphql/queries";
import {API, graphqlOperation} from "aws-amplify";
import {Table} from "antd";
import parseMatchData from "../utils/parseMatchData";

class DisplayMatches extends Component {
  state = {
    matches: [],
    teams: [],
  };

  componentDidMount = async () => {
    const matches = await this.getMatches();
    const teams = await this.getTeams();
    this.setState({
      matches,
      teams,
    });
  };

  getMatches = async () => {
    const result = await API.graphql(graphqlOperation(listMatchs));
    console.log("All matches", result.data.listMatchs.items);
    return result.data.listMatchs.items.sort((match, match2) => {
      return Date.parse(match.date) > Date.parse(match2.date);
    });
  };

  getTeams = async () => {
    console.log("Hello getTeams");
    const result = await API.graphql(graphqlOperation(listTeams));
    console.log("goodbye getTeams", result);
    console.log("All teams", result.data.listTeams.items);
    return result.data.listTeams.items;
  };

  render() {
    const columns = [
      {
        title: "Team Name",
        dataIndex: "teamName",
        key: "teamName",
        render: (text) => <a>{text}</a>,
      },
      {
        title: "Points",
        dataIndex: "points",
        key: "points",
      },
    ];

    const {matches, teams} = this.state;
    console.log(matches, teams);
    if (matches.length === 0 || teams.length === 0) {
      return <div>Loading... (no matches found)</div>;
    }

    const data = teams
      .map((team) => {
        const homePoints = team.homeMatches.items.reduce((acc, match) => {
          return (
            acc +
            parseMatchData(match).filter((datum) => datum.vs === "⬅️").length
          );
        }, 0);
        const awayPoints = team.awayMatches.items.reduce((acc, match) => {
          return (
            acc +
            parseMatchData(match).filter((datum) => datum.vs === "➡️").length
          );
        }, 0);
        return {
          teamName: team.name,
          points: homePoints + awayPoints,
        };
      })
      .sort((team1, team2) => {
        return team1.points > team2.points;
      });

    return <Table columns={columns} dataSource={data} pagination={false} />;
  }
}

export default DisplayMatches;
